### PR TITLE
Disable/Enable a user

### PR DESCRIPTION
**Pull request by santiagodoldan**

### CODE REVIEW

**Comment by JordyLangen** [comment]
Maybe update the README with the new command?

**Comment by JordyLangen** [comment]
:+1:

**Comment by santiagodoldan** [comment]
@JordyLangen this is not a new command (at least now), this is part of the new users index page, there you have a checkbox to change this flag.

if you pull latest changes you will find lot of new features, let me know what do you think about them.

Cheers

**Comment by JordyLangen** [comment]
@santiagodoldan Already deleted that comment after looking into it more deeply. Never did any Ruby and trying to learn thourgh personal projects and open source

**Comment by santiagodoldan** [comment]
yep, that's the best way to learn any new language.

**Pull request merged**
